#!/usr/bin/env python3
"""Fill SanYiCAD_zh.ts translations and remove unfinished markers."""
import re
import xml.sax.saxutils as xml
from pathlib import Path

TS_PATH = Path(__file__).resolve().parents[2] / "UI" / "Common" / "Translations" / "SanYiCAD_zh.ts"

# English -> Simplified Chinese
TRANSLATIONS = {
    "Copy Info": "复制信息",
    "SanYi CAD": "三一 CAD",
    "Computer-Aided Design Software": "计算机辅助设计软件",
    "SanYi3D": "三一 3D",
    "3D Model Viewer based on Qt and OpenGL": "基于 Qt 与 OpenGL 的三维模型查看器",
    "Software Information": "软件信息",
    "Version:": "版本：",
    "Build Date:": "构建日期：",
    "Compiler:": "编译器：",
    "Language Standard:": "语言标准：",
    "Qt Version:": "Qt 版本：",
    "System Information": "系统信息",
    "OS:": "操作系统：",
    "CPU:": "处理器：",
    "Memory:": "内存：",
    "Screen:": "屏幕：",
    "N/A": "无",
    "OpenGL Information": "OpenGL 信息",
    "Vendor:": "厂商：",
    "Renderer:": "渲染器：",
    "GLSL:": "GLSL：",
    "Legal": "法律信息",
    "Built with Qt": "基于 Qt 构建",
    "This software uses the Qt framework (LGPL v3). Qt source is available at:": "本软件使用 Qt 框架（LGPL v3）。Qt 源代码可在以下地址获取：",
    "Third-party components are property of their respective owners.": "第三方组件归其各自所有者所有。",
    "%1 (%2 cores)": "%1（%2 核）",
    "%1 GB": "%1 GB",
    "%1x%2 @ %3 DPI (DPR %4)": "%1×%2 @ %3 DPI（DPR %4）",
    "Version": "版本",
    "Build Date": "构建日期",
    "Compiler": "编译器",
    "Language Standard": "语言标准",
    "Qt Version": "Qt 版本",
    "OS": "操作系统",
    "CPU": "处理器",
    "Memory": "内存",
    "Screen": "屏幕",
    "Vendor": "厂商",
    "Renderer": "渲染器",
    "GLSL": "GLSL",
    "Scene manager not ready.": "场景管理器未就绪。",
    "No entities to offset.": "没有可偏移的图元。",
    "Array": "阵列",
    "No entities selected for array.": "未选择用于阵列的图元。",
    "No entities selected for array": "未选择用于阵列的图元",
    "Array...": "阵列...",
    "Type:": "类型：",
    "Rectangular Array": "矩形阵列",
    "Circular Array": "环形阵列",
    "Rectangular Parameters": "矩形参数",
    "Rows:": "行数：",
    "Columns:": "列数：",
    "Row Spacing:": "行间距：",
    "Column Spacing:": "列间距：",
    "Circular Parameters": "环形参数",
    "Count:": "数量：",
    "Angle (deg):": "角度（度）：",
    "Radius:": "半径：",
    "Invalid parameters": "参数无效",
    "Camera": "相机",
    "Speed": "速度",
    "Move:": "移动：",
    "Rotate:": "旋转：",
    "Zoom:": "缩放：",
    "Mode": "模式",
    "Perspective": "透视",
    "Orthographic": "正交",
    "Default": "默认",
    "Trackball": "轨迹球",
    "Fly": "飞行",
    "Array created %1 entities": "阵列已创建 %1 个图元",
    "Array operation failed": "阵列操作失败",
    "Array Calculation": "阵列计算",
    "Array cancelled": "阵列已取消",
    "Array completed: %1 new entities": "阵列完成：新增 %1 个图元",
    "Array did not complete": "阵列未完成",
    "Array is already running": "阵列正在运行中",
    "Cloning entities...": "正在克隆图元...",
    "SceneEditService unavailable": "场景编辑服务不可用",
    "Align": "对齐",
    "Properties": "属性",
    "Close": "关闭",
    "Property": "属性",
    "Value": "值",
    "UI Font Size": "界面字体大小",
    "Font Size:": "字体大小：",
    "Preview": "预览",
    "AaBbCcXxYyZz  1234567890  ": "AaBbCcXxYyZz  1234567890  ",
    "AaBbCcXxYyZz  1234567890  \nThe quick brown fox jumps over the lazy dog.": "AaBbCcXxYyZz  1234567890  \n敏捷的棕色狐狸跳过懒狗。",
    "The quick brown fox jumps over the lazy dog.": "敏捷的棕色狐狸跳过懒狗。",
    "m": "米",
    "mil": "密尔",
    "pixel": "像素",
    "Enable Log": "启用日志",
    "Trace": "跟踪",
    "Debug": "调试",
    "Warn": "警告",
    "Critical": "严重",
    "Off": "关闭",
    "Display Unit:": "显示单位：",
    "Language:": "语言：",
    "Log Enabled:": "日志启用：",
    "Log Level:": "日志级别：",
    "Open Log Folder": "打开日志文件夹",
    "Failed to open log folder:\n": "无法打开日志文件夹：\n",
    "Log Files:": "日志文件：",
    "Show Grid:": "显示网格：",
    "Major Grid Spacing:": "主网格间距：",
    "Major Line Width:": "主线宽度：",
    "Minor Line Width:": "次线宽度：",
    "Major:": "主网格：",
    "Minor:": "次网格：",
    "Layer Properties": "图层属性",
    "Name:": "名称：",
    "Pick Color...": "选择颜色...",
    "Color:": "颜色：",
    "Locked": "锁定",
    "Entities: 0": "图元：0",
    "Contents:": "内容：",
    "Rename": "重命名",
    "Set Current": "设为当前",
    "%1 (ID %2, %3 entities)": "%1（ID %2，%3 个图元）",
    " [Current]": " [当前]",
    "Entities: %1": "图元：%1",
    "Layer Color": "图层颜色",
    "Front view (1)": "前视图 (1)",
    "Back view (2)": "后视图 (2)",
    "Left view (3)": "左视图 (3)",
    "Right view (4)": "右视图 (4)",
    "Top view (5)": "顶视图 (5)",
    "Bottom view (6)": "底视图 (6)",
    "ISO": "等轴测",
    "Isometric view (Alt+I)": "等轴测视图 (Alt+I)",
    "Reset": "重置",
    "Reset view (R)": "重置视图 (R)",
    "Fit": "适应",
    "Fit all (F)": "适应全部 (F)",
    "Lighting": "光照",
    "Ambient": "环境光",
    "Enabled": "启用",
    "Intensity:": "强度：",
    "Directional": "定向光",
    "Shadow": "阴影",
    "Quality:": "质量：",
    "Shortcut Conflicts": "快捷键冲突",
    "Detected %1 shortcut conflict(s). See log for details.": "检测到 %1 个快捷键冲突。详情请查看日志。",
    "Layer: %1 — %2": "图层：%1 — %2",
    "Online documentation is not configured yet.": "在线文档尚未配置。",
    "SanYi3D - 3D Model Viewer": "三一 3D - 三维模型查看器",
    "SanYi3D - %1": "三一 3D - %1",
    "Unnamed": "未命名",
    "%1 models": "%1 个模型",
    "RMB=Rotate | MMB=Pan | Wheel=Zoom | 1-6=Views | Alt+I/D/T=Axonometric": "右键=旋转 | 中键=平移 | 滚轮=缩放 | 1-6=视图 | Alt+I/D/T=轴测",
    "Sheet": "板材",
    "Spacing": "间距",
    "Orientation": "方向",
    "Enable rotation": "启用旋转",
    "Rotation angles:": "旋转角度：",
    "Enable mirror (flip X)": "启用镜像（X 轴翻转）",
    "Parts": "零件",
    "Nest selected entities only (use all if none selected)": "仅排样选中图元（未选中时使用全部）",
    "Quantity per part:": "每个零件数量：",
    "Iterations:": "迭代次数：",
    "Time limit (ms):": "时间限制（毫秒）：",
    "Sort strategy:": "排序策略：",
    "By area DESC": "按面积降序",
    "By longest edge DESC": "按最长边降序",
    "By width DESC": "按宽度降序",
    "By height DESC": "按高度降序",
    "Nesting Calculation": "排样计算",
    "Initializing...": "正在初始化...",
    "Progress": "进度",
    "Preparing...": "正在准备...",
    "%p%": "%p%",
    "Elapsed: 0 seconds": "已用时间：0 秒",
    "Canceling...": "正在取消...",
    "Canceled": "已取消",
    "Completed": "已完成",
    "Finished": "完成",
    "Elapsed: %1": "已用时间：%1",
    "%1 seconds": "%1 秒",
    "Confirm Cancel": "确认取消",
    "Task is in progress, are you sure you want to cancel?": "任务正在进行中，确定要取消吗？",
    "Layer Manager...": "图层管理器...",
    "Rotate 90° CW": "顺时针旋转 90°",
    "Rotate 90° CCW": "逆时针旋转 90°",
    "Rotate 180°": "旋转 180°",
    "Split parameter t must be in (0, 1), got %1": "分割参数 t 必须在 (0, 1) 范围内，当前为 %1",
    "No entities selected for split": "未选择用于分割的图元",
    "No bezier entities in selection": "选中项中没有贝塞尔图元",
    "Discretize produced no output": "离散化未产生输出",
    "Discretize not implemented (computed %1 lines, %2 points, result discarded)": "离散化未实现（已计算 %1 条线、%2 个点，结果已丢弃）",
    "Move dialog opened": "移动对话框已打开",
    "Array dialog opened": "阵列对话框已打开",
    "MainWindow is not available": "主窗口不可用",
    "Algorithm adapter is not available": "算法适配器不可用",
    "Fill dialog opened": "填充对话框已打开",
    "Nesting dialog opened": "排样对话框已打开",
    "Offset dialog opened": "偏移对话框已打开",
    "Split %1 bezier at t=%2": "在 t=%2 处分割 %1 条贝塞尔曲线",
    "Laser connecting...": "激光器连接中...",
    "Laser disconnected": "激光器已断开",
    "Test fire executed": "试射已执行",
    "Material Database - %1 materials loaded": "材料数据库 - 已加载 %1 种材料",
    "Process Parameters dialog": "工艺参数对话框",
    "EMERGENCY STOP activated!": "紧急停止已激活！",
    "Safety reset": "安全复位",
    "Self check passed": "自检通过",
    "Self check FAILED": "自检失败",
    "Set Current Layer": "设为当前图层",
    "Move to Layer...": "移动到图层...",
    "Settings applied and saved": "设置已应用并保存",
    "Laser: %1": "激光器：%1",
    "Laser connected": "激光器已连接",
    "Laser error: %1": "激光器错误：%1",
    "EMERGENCY STOP - System halted": "紧急停止 - 系统已停机",
    "Multiple Selection": "多选",
    "Count": "数量",
    "Min": "最小",
    "Max": "最大",
    "Width": "宽度",
    "Height": "高度",
    "Properties...": "属性...",
    "Layers": "图层",
    "Layer: %1 (%2)": "图层：%1（%2）",
    " [Locked]": " [锁定]",
    " [Hidden]": " [隐藏]",
    "Switch to layer %1 (%2)": "切换到图层 %1（%2）",
    "Layer color %1": "图层颜色 %1",
    "Display": "显示",
    "Wireframe mode (W)": "线框模式 (W)",
    "Show grid (G)": "显示网格 (G)",
    "BBox": "包围盒",
    "Show bounding box (B)": "显示包围盒 (B)",
    "Floor": "地面",
    "Show floor (F)": "显示地面 (F)",
    "Translate mode (T)": "平移模式 (T)",
    "Rotate mode (R)": "旋转模式 (R)",
    "Scale mode (S)": "缩放模式 (S)",
    "Top Ruler": "顶部标尺",
    "Top:": "顶部：",
    "Left Ruler": "左侧标尺",
    "Left:": "左侧：",
    "Thickness:": "厚度：",
    "Major Tick:": "主刻度：",
    "Bg:": "背景：",
    "Tick:": "刻度：",
    "Text:": "文字：",
    "Settings - 2D": "设置 - 二维",
    "Settings - 3D": "设置 - 三维",
    "Category:": "分类：",
    "All": "全部",
    "Tool": "工具",
    "Render": "渲染",
    "Action": "操作",
    "Category": "分类",
    "Shortcut": "快捷键",
    "Edit...": "编辑...",
    "Reset to Default": "恢复默认",
    "Reset All": "全部重置",
    "Edit Shortcut": "编辑快捷键",
    "Please select a shortcut to edit.": "请选择要编辑的快捷键。",
    "Press Shortcut Key": "按下快捷键",
    "Press the key combination for:": "请按下以下操作的快捷键组合：",
    "Press the key combination for:\n%1": "请为 %1 按下快捷键组合：",
    "%1": "%1",
    "Clear": "清除",
    "(None)": "（无）",
    "'%1' and '%2' share the same shortcut": "“%1”和“%2”使用了相同的快捷键",
    "&apos;%1&apos; and &apos;%2&apos; share the same shortcut": "“%1”和“%2”使用了相同的快捷键",
    "Reset All Shortcuts": "重置全部快捷键",
    "Are you sure you want to reset all shortcuts to their default values?": "确定要将所有快捷键恢复为默认值吗？",
    "Enable Snap": "启用捕捉",
    "Snap Radius:": "捕捉半径：",
    "Polar Angle Step:": "极轴角度步长：",
    "Snap Modes": "捕捉模式",
    "Endpoint": "端点",
    "Midpoint": "中点",
    "Center": "圆心",
    "Node": "节点",
    "Quadrant": "象限",
    "Intersection": "交点",
    "Perpendicular": "垂足",
    "Tangent": "切点",
    "Nearest": "最近点",
    "Grid Style (GSM)": "网格样式 (GSM)",
    "Spacing:": "间距：",
    "Lines": "线",
    "Dots": "点",
    "Cross": "十字",
    "Major Every:": "主网格间隔：",
    "Selected: 0": "已选：0",
    "Selected: %1  W: %2  H: %3": "已选：%1  宽：%2  高：%3",
    "Position:(0.00, 0.00, 0.00)": "位置：(0.00, 0.00, 0.00)",
    "Model: -": "模型：-",
    "Selected: %1": "已选：%1",
    "Model: %1 | Triangles: %2": "模型：%1 | 三角形：%2",
    "Model: %1": "模型：%1",
    "Position:(%1, %2) %3": "位置：(%1, %2) %3",
    "Select all models": "全选模型",
    "Camera Frustum": "相机视锥",
    "Field of View:": "视野：",
    "Near Plane:": "近裁剪面：",
    "Far Plane:": "远裁剪面：",
    "Effects": "效果",
    "Enable Fog": "启用雾效",
    "Anti-Aliasing": "抗锯齿",
    "MSAA Samples:": "MSAA 采样：",
    "Moved selection to layer %1": "已将选中项移动到图层 %1",
    "Vision operation executed": "视觉操作已执行",
    "Vision processor is not initialized.": "视觉处理器未初始化。",
    "Vision module is not available. Build with BUILD_VISION=ON to use this feature.": "视觉模块不可用。请使用 BUILD_VISION=ON 构建以启用此功能。",
    "3D Models (*.stl *.STL *.obj *.OBJ);;All Files (*.*)": "三维模型 (*.stl *.STL *.obj *.OBJ);;所有文件 (*.*)",
    "Clear Selection\tEsc": "清除选择\tEsc",
    "Delete\tDel": "删除\tDel",
    "Fit All\tCtrl+F": "适应全部\tCtrl+F",
    "Front/Back/Left/Right/Top/Bottom\t1-6": "前/后/左/右/顶/底\t1-6",
    "Import Model\tCtrl+Shift+O": "导入模型\tCtrl+Shift+O",
    "Import Model...": "导入模型...",
    "Isometric/Dimetric/Trimetric\tAlt+I / Alt+D / Alt+T": "等轴测/二轴测/三轴测\tAlt+I / Alt+D / Alt+T",
    "New Scene": "新建场景",
    "New Scene\tCtrl+N": "新建场景\tCtrl+N",
    "Open Model\tCtrl+O": "打开模型\tCtrl+O",
    "Redo\tCtrl+Y": "重做\tCtrl+Y",
    "Reset View\tCtrl+R": "重置视图\tCtrl+R",
    "Rotate\tR": "旋转\tR",
    "Scale\tS": "缩放\tS",
    "Select All\tCtrl+A": "全选\tCtrl+A",
    "Switch to 2D\tCtrl+Shift+2": "切换到二维\tCtrl+Shift+2",
    "The scene has unsaved changes. Continue anyway?": "场景有未保存的更改。仍要继续吗？",
    "The scene has unsaved changes. Exit anyway?": "场景有未保存的更改。仍要退出吗？",
    "Translate\tT": "平移\tT",
    "Undo\tCtrl+Z": "撤销\tCtrl+Z",
    # Shortcuts (context Shortcuts)
    "Select Tool": "选择工具",
    "Point Tool": "点工具",
    "Line Tool": "直线工具",
    "Polyline Tool": "多段线工具",
    "Polygon Tool": "多边形工具",
    "Circle Tool": "圆工具",
    "Arc Tool": "圆弧工具",
    "Ellipse Tool": "椭圆工具",
    "Rectangle Tool": "矩形工具",
    "Triangle Tool": "三角形工具",
    "Quadratic Bezier": "二次贝塞尔",
    "Cubic Bezier": "三次贝塞尔",
    "Spline Tool": "样条工具",
    "NURBS Tool": "NURBS 工具",
    "Smart Line Tool": "智能线工具",
    "Text Tool": "文字工具",
    "Bitmap Tool": "位图工具",
    "QR Code Tool": "二维码工具",
    "Delete": "删除",
    "Copy": "复制",
    "Cut": "剪切",
    "Paste": "粘贴",
    "Select All": "全选",
    "Undo": "撤销",
    "Redo": "重做",
    "Save": "保存",
    "Save As": "另存为",
    "New File": "新建文件",
    "Open File": "打开文件",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Pan Up": "向上平移",
    "Pan Down": "向下平移",
    "Pan Left": "向左平移",
    "Pan Right": "向右平移",
    "Reset View": "重置视图",
    "Zoom to Fit": "适应窗口",
    "Zoom to Selection": "缩放到选中",
    "Toggle Antialiasing": "切换抗锯齿",
    "Toggle Wireframe": "切换线框",
    "Toggle Depth Test": "切换深度测试",
    "Reset Render View": "重置渲染视图",
    # Shortcut categories
    "Edit": "编辑",
    "View": "视图",
}


def escape_ts(text: str) -> str:
    return xml.escape(text, entities={"'": "&apos;", '"': "&quot;"})


def process_message(block: str) -> tuple[str, bool]:
    src_m = re.search(r"<source>(.*?)</source>", block, re.DOTALL)
    if not src_m:
        return block, False
    source = src_m.group(1)

    tr_m = re.search(r"<translation([^>]*)>(.*?)</translation>", block, re.DOTALL)
    if not tr_m:
        return block, False

    attrs = tr_m.group(1)
    translation = tr_m.group(2)
    changed = False

    if 'type="unfinished"' not in attrs:
        return block, False

    current = translation.strip()
    if current and current != source:
        new_text = current
    elif source in TRANSLATIONS:
        new_text = TRANSLATIONS[source]
        changed = True
    else:
        return block, False

    new_block = block
    new_block = re.sub(
        r"<translation[^>]*>.*?</translation>",
        f"<translation>{escape_ts(new_text)}</translation>",
        new_block,
        count=1,
        flags=re.DOTALL,
    )
    changed = True
    return new_block, changed


def main():
    text = TS_PATH.read_text(encoding="utf-8")
    blocks = list(re.finditer(r"<message>.*?</message>", text, re.DOTALL))
    updated = 0
    missing = set()

    for match in blocks:
        old = match.group(0)
        new, changed = process_message(old)
        if changed:
            text = text.replace(old, new, 1)
            updated += 1
        elif 'type="unfinished"' in old:
            src_m = re.search(r"<source>(.*?)</source>", old, re.DOTALL)
            if src_m:
                src = src_m.group(1)
                tr_m = re.search(r"<translation[^>]*>(.*?)</translation>", old, re.DOTALL)
                cur = tr_m.group(1).strip() if tr_m else ""
                if not cur or cur == src:
                    missing.add(src)

    TS_PATH.write_text(text, encoding="utf-8")
    print(f"Updated {updated} messages in {TS_PATH}")
    if missing:
        print(f"Still missing translations ({len(missing)}):")
        for s in sorted(missing):
            print(f"  {s!r}")


if __name__ == "__main__":
    main()
